### PR TITLE
Channel name fix

### LINKED ISSUE #36: Channel name are case sensitive
These command are not the same but for HexChat it is.
```
JOIN #hello
JOIN #Hello
```

### PR DESCRIPTION
**Pull request by deydoux**
This pull request includes several changes to improve the handling of channels and client interactions in the IRC server codebase. The most important changes include adding a utility function to check for valid channel prefixes, modifying how channel names are handled to ensure case insensitivity, and refactoring several methods to enhance readability and maintainability.

### Channel Prefix Handling:
* Added `is_prefix` method to check for valid channel prefixes (`#` or `&`) in `Channel` class (`include/class/Channel.hpp`, `src/class/Channel.cpp`). [[1]](diffhunk://#diff-e948e43ff1c57d90d61f9c64c956866cbea25bf4d9f2b56a8bf99141078f5186R46) [[2]](diffhunk://#diff-9561c03c8d58c688baa36075b0c781a8bb977e74f6e2dd6a6322fe072f9b1bd3R31-R43)

### Case Insensitivity:
* Modified `Client::is_channel_operator` and `Server::get_channel` methods to handle channel names case insensitively (`src/class/Client.cpp`, `src/class/Server.cpp`). [[1]](diffhunk://#diff-7d98473a6ad047567921f5109c8e0e5e9786dcfee60fbba04989116279823e61L132-R138) [[2]](diffhunk://#diff-4db7d92b4e2abe7ef080ae359bcbdf72eb873324e1e960d83a354ac0f090a793L433-L436)
* Updated `Command::_join` and `Command::_names` methods to use the correct channel names and ensure case insensitivity (`src/class/Command.cpp`). [[1]](diffhunk://#diff-99a875f4ebda4f241f0846ef7136b71a5236683f6c434eea4e59412a74a2a0a1R115-R139) [[2]](diffhunk://#diff-99a875f4ebda4f241f0846ef7136b71a5236683f6c434eea4e59412a74a2a0a1L497-R489)

### Code Refactoring:
* Refactored `Command::_join` and `Command::_kick` methods to improve readability and maintainability (`src/class/Command.cpp`). [[1]](diffhunk://#diff-99a875f4ebda4f241f0846ef7136b71a5236683f6c434eea4e59412a74a2a0a1L154-R160) [[2]](diffhunk://#diff-99a875f4ebda4f241f0846ef7136b71a5236683f6c434eea4e59412a74a2a0a1L230-R235)
* Simplified `Command::_topic` and `Command::_privmsg` methods by combining multiple lines of code into single lines for better clarity (`src/class/Command.cpp`). [[1]](diffhunk://#diff-99a875f4ebda4f241f0846ef7136b71a5236683f6c434eea4e59412a74a2a0a1R368-R377) [[2]](diffhunk://#diff-99a875f4ebda4f241f0846ef7136b71a5236683f6c434eea4e59412a74a2a0a1L211-R204)

### Channel Deletion:
* Enhanced `Server::delete_channel` method to ensure proper deletion of channels by checking for channel existence before erasure (`src/class/Server.cpp`).

### CODE REVIEW

File: src/class/Command.cpp [hunk 1]
```diff
@@ -403,11 +388,12 @@ void Command::_topic(const args_t &args, Client &client)
...
 	channel->set_topic(client, new_topic);
-	channel->send_broadcast(client.create_cmd_reply(
-		client.get_mask(), "TOPIC", channel_name, new_topic
-	));
+	channel->send_broadcast(
+		client.create_cmd_reply(client.get_mask(), "TOPIC", channel_name, new_topic)
+	);
 }
 
+// TODO ensure channel case insensitivity doesn't break
```
Comment (deydoux) [inline src/class/Command.cpp]: @qterisse

File: src/class/Command.cpp [hunk 2]
```diff
@@ -467,6 +453,7 @@ void Command::_hk(const args_t &args, Client &client)
 	client.reply(RPL_HK, "", message);
 }
 
+// TODO ensure channel case insensitivity doesn't break
```
Comment (deydoux) [inline src/class/Command.cpp]: @qterisse

**Review by qpeachy — APPROVED** [review]
